name: 1. DevStageProdPipeline

on:
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo Building...
        
  unittest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: UnitTest
        run: echo Unit tests...
        
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: echo Linting...
        
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [unittest, lint]
    environment: development
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo Deploying to dev...
        
  test-dev:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo Testing dev...
        
  deploy-stage:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: [unittest, lint]
    environment: stage
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo Deploying to stage...
        
  test-stage:
    runs-on: ubuntu-latest
    needs: [deploy-stage]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo Testing stage...
        
  deploy-production:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: [test-stage]
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo Deploying to prod
        
  test-production:
    runs-on: ubuntu-latest
    needs: [deploy-production]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo Testing prod
