name: 3. ManualTriggerDevDeploy

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: dev

  test-dev:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/apitest
        with:
          environment: dev
