name: 3. ReleaseTriggerStageProdDeploy

on:
  release:
    types: [published]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: stage

  test-stage:
    runs-on: ubuntu-latest
    needs: [deploy-stage]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/apitest
        with:
          environment: stage

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [test-stage]
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: prod

  test-prod:
    runs-on: ubuntu-latest
    needs: [deploy-prod]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/apitest
        with:
          environment: prod
