name: Test approval
on: [workflow_dispatch]


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      
  prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo hello
