on: [workflow_dispatch]

jobs:
  approval:
    runs-on: ubuntu-latest
    environment: cr
    steps:
      - name: Retrieve approval comment
        run: |
          echo "Approval comment: ${{ github.event }}"


      - name: github
        run: |
          echo "${{ github }}"
