on: [workflow_dispatch]

jobs:
  approval:
    runs-on: ubuntu-latest
    environment: cr
    steps:
      - name: Retrieve approval comment
        run: |
          echo ${{ toJson(github) }}


      - name: github
        run: |
          echo ${{ toJson(github) }}
